# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from drrobot_jaguar4x4_player/KFodom.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class KFodom(genpy.Message):
  _md5sum = "dbaa4aa231e888ba44311921aa92587c"
  _type = "drrobot_jaguar4x4_player/KFodom"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 deltaD
float32 deltatheta
float32 Ddot
float32 thetadot
"""
  __slots__ = ['deltaD','deltatheta','Ddot','thetadot']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       deltaD,deltatheta,Ddot,thetadot

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(KFodom, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.deltaD is None:
        self.deltaD = 0.
      if self.deltatheta is None:
        self.deltatheta = 0.
      if self.Ddot is None:
        self.Ddot = 0.
      if self.thetadot is None:
        self.thetadot = 0.
    else:
      self.deltaD = 0.
      self.deltatheta = 0.
      self.Ddot = 0.
      self.thetadot = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.deltaD, _x.deltatheta, _x.Ddot, _x.thetadot))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.deltaD, _x.deltatheta, _x.Ddot, _x.thetadot,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.deltaD, _x.deltatheta, _x.Ddot, _x.thetadot))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.deltaD, _x.deltatheta, _x.Ddot, _x.thetadot,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
