# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from drrobot_jaguar4x4_player/Rscanpose.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Rscanpose(genpy.Message):
  _md5sum = "1b2170f99f4bd314082e9742552d3d71"
  _type = "drrobot_jaguar4x4_player/Rscanpose"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32[645] Rscanpose
"""
  __slots__ = ['Rscanpose']
  _slot_types = ['float32[645]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Rscanpose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Rscanpose, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Rscanpose is None:
        self.Rscanpose = [0.] * 645
    else:
      self.Rscanpose = [0.] * 645

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_645f().pack(*self.Rscanpose))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 2580
      self.Rscanpose = _get_struct_645f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.Rscanpose.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 2580
      self.Rscanpose = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=645)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_645f = None
def _get_struct_645f():
    global _struct_645f
    if _struct_645f is None:
        _struct_645f = struct.Struct("<645f")
    return _struct_645f
