/* Auto-generated by genmsg_cpp for file /home/bgs/catkin_ws/H20_motion/drrobot_jaguar4x4_player/msg/KFodom.msg */
#ifndef DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_KFODOM_H
#define DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_KFODOM_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace drrobot_jaguar4x4_player
{
template <class ContainerAllocator>
struct KFodom_ {
  typedef KFodom_<ContainerAllocator> Type;

  KFodom_()
  : deltaD(0.0)
  , deltatheta(0.0)
  , Ddot(0.0)
  , thetadot(0.0)
  {
  }

  KFodom_(const ContainerAllocator& _alloc)
  : deltaD(0.0)
  , deltatheta(0.0)
  , Ddot(0.0)
  , thetadot(0.0)
  {
  }

  typedef float _deltaD_type;
  float deltaD;

  typedef float _deltatheta_type;
  float deltatheta;

  typedef float _Ddot_type;
  float Ddot;

  typedef float _thetadot_type;
  float thetadot;


  typedef boost::shared_ptr< ::drrobot_jaguar4x4_player::KFodom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drrobot_jaguar4x4_player::KFodom_<ContainerAllocator>  const> ConstPtr;
}; // struct KFodom
typedef  ::drrobot_jaguar4x4_player::KFodom_<std::allocator<void> > KFodom;

typedef boost::shared_ptr< ::drrobot_jaguar4x4_player::KFodom> KFodomPtr;
typedef boost::shared_ptr< ::drrobot_jaguar4x4_player::KFodom const> KFodomConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::drrobot_jaguar4x4_player::KFodom_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::drrobot_jaguar4x4_player::KFodom_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace drrobot_jaguar4x4_player

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::drrobot_jaguar4x4_player::KFodom_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::drrobot_jaguar4x4_player::KFodom_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::drrobot_jaguar4x4_player::KFodom_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dbaa4aa231e888ba44311921aa92587c";
  }

  static const char* value(const  ::drrobot_jaguar4x4_player::KFodom_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdbaa4aa231e888baULL;
  static const uint64_t static_value2 = 0x44311921aa92587cULL;
};

template<class ContainerAllocator>
struct DataType< ::drrobot_jaguar4x4_player::KFodom_<ContainerAllocator> > {
  static const char* value() 
  {
    return "drrobot_jaguar4x4_player/KFodom";
  }

  static const char* value(const  ::drrobot_jaguar4x4_player::KFodom_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::drrobot_jaguar4x4_player::KFodom_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 deltaD\n\
float32 deltatheta\n\
float32 Ddot\n\
float32 thetadot\n\
\n\
";
  }

  static const char* value(const  ::drrobot_jaguar4x4_player::KFodom_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::drrobot_jaguar4x4_player::KFodom_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::drrobot_jaguar4x4_player::KFodom_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.deltaD);
    stream.next(m.deltatheta);
    stream.next(m.Ddot);
    stream.next(m.thetadot);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct KFodom_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drrobot_jaguar4x4_player::KFodom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::drrobot_jaguar4x4_player::KFodom_<ContainerAllocator> & v) 
  {
    s << indent << "deltaD: ";
    Printer<float>::stream(s, indent + "  ", v.deltaD);
    s << indent << "deltatheta: ";
    Printer<float>::stream(s, indent + "  ", v.deltatheta);
    s << indent << "Ddot: ";
    Printer<float>::stream(s, indent + "  ", v.Ddot);
    s << indent << "thetadot: ";
    Printer<float>::stream(s, indent + "  ", v.thetadot);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_KFODOM_H

