/* Auto-generated by genmsg_cpp for file /home/bgs/catkin_ws/H20_motion/drrobot_jaguar4x4_player/msg/MotorInfo.msg */
#ifndef DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_MOTORINFO_H
#define DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_MOTORINFO_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace drrobot_jaguar4x4_player
{
template <class ContainerAllocator>
struct MotorInfo_ {
  typedef MotorInfo_<ContainerAllocator> Type;

  MotorInfo_()
  : header()
  , robot_type()
  , encoder_pos(0)
  , encoder_vel(0)
  , encoder_dir(0)
  , motor_current(0.0)
  , motor_pwm(0)
  {
  }

  MotorInfo_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , robot_type(_alloc)
  , encoder_pos(0)
  , encoder_vel(0)
  , encoder_dir(0)
  , motor_current(0.0)
  , motor_pwm(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_type_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  robot_type;

  typedef uint32_t _encoder_pos_type;
  uint32_t encoder_pos;

  typedef uint32_t _encoder_vel_type;
  uint32_t encoder_vel;

  typedef uint32_t _encoder_dir_type;
  uint32_t encoder_dir;

  typedef float _motor_current_type;
  float motor_current;

  typedef uint32_t _motor_pwm_type;
  uint32_t motor_pwm;


  typedef boost::shared_ptr< ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator>  const> ConstPtr;
}; // struct MotorInfo
typedef  ::drrobot_jaguar4x4_player::MotorInfo_<std::allocator<void> > MotorInfo;

typedef boost::shared_ptr< ::drrobot_jaguar4x4_player::MotorInfo> MotorInfoPtr;
typedef boost::shared_ptr< ::drrobot_jaguar4x4_player::MotorInfo const> MotorInfoConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace drrobot_jaguar4x4_player

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9e31f4f22948e8b2ee140c8cc701e042";
  }

  static const char* value(const  ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9e31f4f22948e8b2ULL;
  static const uint64_t static_value2 = 0xee140c8cc701e042ULL;
};

template<class ContainerAllocator>
struct DataType< ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "drrobot_jaguar4x4_player/MotorInfo";
  }

  static const char* value(const  ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# motor sensor data message from DrRobot Robot.\n\
\n\
Header header    	# timestamp in the header is the time the driver\n\
		 	# returned the battery/power reading\n\
string robot_type	# robot type, I90 series, sentinel3 or Jaguar Power/Motion\n\
\n\
uint32 encoder_pos	# encoder positon count\n\
uint32 encoder_vel	# encoder velocity value\n\
uint32 encoder_dir	# encoder direction\n\
\n\
float32 motor_current	# motor current\n\
uint32 motor_pwm	# output PWM value, only for Jaguar series robot\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.robot_type);
    stream.next(m.encoder_pos);
    stream.next(m.encoder_vel);
    stream.next(m.encoder_dir);
    stream.next(m.motor_current);
    stream.next(m.motor_pwm);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct MotorInfo_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::drrobot_jaguar4x4_player::MotorInfo_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_type);
    s << indent << "encoder_pos: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.encoder_pos);
    s << indent << "encoder_vel: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.encoder_vel);
    s << indent << "encoder_dir: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.encoder_dir);
    s << indent << "motor_current: ";
    Printer<float>::stream(s, indent + "  ", v.motor_current);
    s << indent << "motor_pwm: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.motor_pwm);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_MOTORINFO_H

