/* Auto-generated by genmsg_cpp for file /home/bgs/catkin_ws/H20_motion/drrobot_jaguar4x4_player/msg/variable.msg */
#ifndef DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_VARIABLE_H
#define DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_VARIABLE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace drrobot_jaguar4x4_player
{
template <class ContainerAllocator>
struct variable_ {
  typedef variable_<ContainerAllocator> Type;

  variable_()
  : variable0(0.0)
  , variable1(0.0)
  , variable2(0.0)
  {
  }

  variable_(const ContainerAllocator& _alloc)
  : variable0(0.0)
  , variable1(0.0)
  , variable2(0.0)
  {
  }

  typedef float _variable0_type;
  float variable0;

  typedef float _variable1_type;
  float variable1;

  typedef float _variable2_type;
  float variable2;


  typedef boost::shared_ptr< ::drrobot_jaguar4x4_player::variable_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drrobot_jaguar4x4_player::variable_<ContainerAllocator>  const> ConstPtr;
}; // struct variable
typedef  ::drrobot_jaguar4x4_player::variable_<std::allocator<void> > variable;

typedef boost::shared_ptr< ::drrobot_jaguar4x4_player::variable> variablePtr;
typedef boost::shared_ptr< ::drrobot_jaguar4x4_player::variable const> variableConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::drrobot_jaguar4x4_player::variable_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::drrobot_jaguar4x4_player::variable_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace drrobot_jaguar4x4_player

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::drrobot_jaguar4x4_player::variable_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::drrobot_jaguar4x4_player::variable_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::drrobot_jaguar4x4_player::variable_<ContainerAllocator> > {
  static const char* value() 
  {
    return "58885270dd0a2390053b2e1182f5e840";
  }

  static const char* value(const  ::drrobot_jaguar4x4_player::variable_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x58885270dd0a2390ULL;
  static const uint64_t static_value2 = 0x053b2e1182f5e840ULL;
};

template<class ContainerAllocator>
struct DataType< ::drrobot_jaguar4x4_player::variable_<ContainerAllocator> > {
  static const char* value() 
  {
    return "drrobot_jaguar4x4_player/variable";
  }

  static const char* value(const  ::drrobot_jaguar4x4_player::variable_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::drrobot_jaguar4x4_player::variable_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 variable0\n\
float32 variable1\n\
float32 variable2\n\
\n\
";
  }

  static const char* value(const  ::drrobot_jaguar4x4_player::variable_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::drrobot_jaguar4x4_player::variable_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::drrobot_jaguar4x4_player::variable_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.variable0);
    stream.next(m.variable1);
    stream.next(m.variable2);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct variable_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drrobot_jaguar4x4_player::variable_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::drrobot_jaguar4x4_player::variable_<ContainerAllocator> & v) 
  {
    s << indent << "variable0: ";
    Printer<float>::stream(s, indent + "  ", v.variable0);
    s << indent << "variable1: ";
    Printer<float>::stream(s, indent + "  ", v.variable1);
    s << indent << "variable2: ";
    Printer<float>::stream(s, indent + "  ", v.variable2);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DRROBOT_JAGUAR4X4_PLAYER_MESSAGE_VARIABLE_H

